export const GET_STOCK = 'stock-check/stock/GET_STOCK'
export const GET_STOCK_SUCCESS = 'stock-check/stock/GET_STOCK_SUCCESS'
export const GET_STOCK_FAIL = 'stock-check/stock/GET_STOCK_FAIL'
export const GET_SYMBOLS = 'stock-check/stock/GET_SYMBOLS'
export const GET_SYMBOLS_SUCCESS = 'stock-check/stock/GET_SYMBOLS_SUCCESS'
export const GET_SYMBOLS_FAIL = 'stock-check/stock/GET_SYMBOLS_FAIL'
export const SET_SYMBOL = 'stock-check/stock/SET_SYMBOL'
export const SET_TAB = 'stock-check/stock/SET_TAB'
export const TOGGLE_FAVORITE = 'stock-check/stock/TOGGLE_FAVORITE'
export const GET_FAVORITES = 'stock-check/stock/GET_FAVORITES'
export const GET_FAVORITES_SUCCESS = 'stock-check/stock/GET_FAVORITES_SUCCESS'
export const GET_FAVORITES_FAIL = 'stock-check/stock/GET_FAVORITES_FAIL'
export const SHOW_AUTOSUGGEST = 'stock-check/stock/SHOW_AUTOSUGGEST'

export const BLUE0 = '#15191d'
export const BLUE1 = '#182129'
export const BLUE2 = '#232f3a'
export const BLUE3 = '#2f4356'

export const TEXT_NORMAL = '#bcc6d9'
export const TEXT_DARK = '#6d788c'

export const RED = '#d23f31'
export const GREEN = '#0f9d58'
export const PINK = '#b257c5'
