export const Actions = {
  GET_STOCK: 'GET_STOCK',
  GET_STOCK_SUCCESS: 'GET_STOCK_SUCCESS',
  GET_STOCK_FAIL: 'GET_STOCK_FAIL',
  GET_SYMBOLS: 'GET_SYMBOLS',
  GET_SYMBOLS_SUCCESS: 'GET_SYMBOLS_SUCCESS',
  GET_SYMBOLS_FAIL: 'GET_SYMBOLS_FAIL',
  SET_SYMBOL: 'SET_SYMBOL',
  SET_TAB: 'SET_TAB',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  GET_FAVORITES: 'GET_FAVORITES',
  GET_FAVORITES_SUCCESS: 'GET_FAVORITES_SUCCESS',
  GET_FAVORITES_FAIL: 'GET_FAVORITES_FAIL',
  CLEAR_FAVORITES: 'CLEAR_FAVORITES',
  SHOW_AUTOSUGGEST: 'SHOW_AUTOSUGGEST'
}
